# Generated by Django 2.2.4 on 2019-08-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_host', models.URLField()),
                ('container_port', models.PositiveIntegerField()),
                ('container_default_message', models.CharField(max_length=255)),
            ],
        ),
    ]
